stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    # params:
    # - data_ingestion.test_size
    outs:
    - data/raw
  data_preprocess:
    cmd: python src/data_preprocess.py
    deps:
    - src/data_preprocess.py
    - data/raw
    outs:
    - data/interim
  feature_engg:
    cmd: python src/feature_engg.py
    deps:
    - src/feature_engg.py
    - data/interim
    # params:
    # - feature_engg.max_features
    outs:
    - data/processed
  model_building:
    cmd: python src/model_building.py
    deps:
    - data/processed
    - src/model_building.py
    outs:
    - models/model.pkl
  model_evaulation:
    cmd: python src/model_evaluation.py
    deps:
    - models/model.pkl
    - src/model_evaluation.py
